int num6;
cout <<"Enter the whole number that is larger than 1" << endl;
cin >> num6;
int num_6 = num6;
num6+=2;
num6 *= num6;
num6 /= 4;
num6 -= num_6;
num6 *= 4;
num6 = sqrt(num6);
cout << "The result is: " << num6 << endl;